### ISSUE TITLE
[Bug] Scarecrow causes extreme amounts of fish to spawn

### ISSUE THREAD

**Issue by SteveoUK** [SuperMartijn642/ScarecrowsTerritory#9]
**Version Info**
- Minecraft, 1.17.1
- Scarecrow's Territory, scarecrowsterritory-1.1.3-mc1.17

**Description of the Bug**
When placed near or on the ocean, it fills with 1000s of mobs, and after 5 or so seconds crashes the game, if use /kill to remove all entities, it will kill thousands.
I did reproduce with only scarecrows territory mod enabled. all overs disabled, same result.

**Steps to Reproduce**
Place over/under or near ocean biome.

**Screenshots**
![2021-10-09_20 10 11](https://user-images.githubusercontent.com/92229741/136671614-442507e8-8b8b-4cfb-9646-12587eb4c057.png)
![2021-10-09_20 08 32](https://user-images.githubusercontent.com/92229741/136671617-2e070680-6117-4826-b34c-105566720184.png)

**Comment by msticninja** [comment]
Same basic issue on 1.16.5. Never seen so many mobs...
![2021-11-09_13 16 59](https://user-images.githubusercontent.com/1581853/140990143-47efa81b-3827-4320-8f23-1392f084e559.png)
.

**Comment by SuperMartijn642** [comment]
Welp, I found the problem. So vanilla uses a factor `/ Math.pow(17, 2)` for calculating mob caps. I accidentally wrote that as `/ 17 * 17` instead of `/ (17 * 17)`. Thus, scarecrows used a mob cab 289 times larger than vanilla. Whoops

I fixed it now in Scarecrows' Territory version 1.1.3b for 1.16 and 1.1.3a for 1.17.
Thank you both for reporting the issue!
